// <auto-generated />
using System;
using FamilyFinance.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyFinance.Infrastructure.Migrations
{
    [DbContext(typeof(FamilyFinanceDbContext))]
    partial class FamilyFinanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FamilyFinance.Domain.Aggregates.Credits.CreditLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FamilyGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PaymentDueDay")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CreditLines", (string)null);
                });

            modelBuilder.Entity("FamilyFinance.Domain.Aggregates.Credits.CreditPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreditLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CreditLineId");

                    b.ToTable("CreditPayments", (string)null);
                });

            modelBuilder.Entity("FamilyFinance.Domain.Aggregates.Expenses.SharedExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("FamilyGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SharedExpenses", (string)null);
                });

            modelBuilder.Entity("FamilyFinance.Domain.Aggregates.FamilyBudget.FamilyGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FamilyGroups", (string)null);
                });

            modelBuilder.Entity("FamilyFinance.Domain.Aggregates.FamilyBudget.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FamilyGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("FamilyGroupId");

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("FamilyFinance.Domain.Aggregates.Credits.CreditLine", b =>
                {
                    b.OwnsOne("FamilyFinance.Domain.ValueObjects.Money", "CreditLimit", b1 =>
                        {
                            b1.Property<Guid>("CreditLineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("CreditLimitAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("CreditLineId");

                            b1.ToTable("CreditLines");

                            b1.WithOwner()
                                .HasForeignKey("CreditLineId");
                        });

                    b.OwnsOne("FamilyFinance.Domain.ValueObjects.Money", "CurrentBalance", b1 =>
                        {
                            b1.Property<Guid>("CreditLineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("CurrentBalanceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("BalanceCurrency");

                            b1.HasKey("CreditLineId");

                            b1.ToTable("CreditLines");

                            b1.WithOwner()
                                .HasForeignKey("CreditLineId");
                        });

                    b.OwnsOne("FamilyFinance.Domain.ValueObjects.Money", "MinimumPayment", b1 =>
                        {
                            b1.Property<Guid>("CreditLineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("MinimumPaymentAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("MinimumPaymentCurrency");

                            b1.HasKey("CreditLineId");

                            b1.ToTable("CreditLines");

                            b1.WithOwner()
                                .HasForeignKey("CreditLineId");
                        });

                    b.OwnsOne("FamilyFinance.Domain.ValueObjects.InterestRate", "AnnualInterestRate", b1 =>
                        {
                            b1.Property<Guid>("CreditLineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AnnualPercentage")
                                .HasPrecision(8, 4)
                                .HasColumnType("decimal(8,4)")
                                .HasColumnName("AnnualInterestRate");

                            b1.HasKey("CreditLineId");

                            b1.ToTable("CreditLines");

                            b1.WithOwner()
                                .HasForeignKey("CreditLineId");
                        });

                    b.Navigation("AnnualInterestRate")
                        .IsRequired();

                    b.Navigation("CreditLimit")
                        .IsRequired();

                    b.Navigation("CurrentBalance")
                        .IsRequired();

                    b.Navigation("MinimumPayment")
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyFinance.Domain.Aggregates.Credits.CreditPayment", b =>
                {
                    b.HasOne("FamilyFinance.Domain.Aggregates.Credits.CreditLine", null)
                        .WithMany("Payments")
                        .HasForeignKey("CreditLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FamilyFinance.Domain.ValueObjects.Money", "InterestPortion", b1 =>
                        {
                            b1.Property<Guid>("CreditPaymentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("InterestAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("InterestCurrency");

                            b1.HasKey("CreditPaymentId");

                            b1.ToTable("CreditPayments");

                            b1.WithOwner()
                                .HasForeignKey("CreditPaymentId");
                        });

                    b.OwnsOne("FamilyFinance.Domain.ValueObjects.Money", "PrincipalPortion", b1 =>
                        {
                            b1.Property<Guid>("CreditPaymentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PrincipalAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("PrincipalCurrency");

                            b1.HasKey("CreditPaymentId");

                            b1.ToTable("CreditPayments");

                            b1.WithOwner()
                                .HasForeignKey("CreditPaymentId");
                        });

                    b.OwnsOne("FamilyFinance.Domain.ValueObjects.Money", "TotalAmount", b1 =>
                        {
                            b1.Property<Guid>("CreditPaymentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("CreditPaymentId");

                            b1.ToTable("CreditPayments");

                            b1.WithOwner()
                                .HasForeignKey("CreditPaymentId");
                        });

                    b.Navigation("InterestPortion")
                        .IsRequired();

                    b.Navigation("PrincipalPortion")
                        .IsRequired();

                    b.Navigation("TotalAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyFinance.Domain.Aggregates.Expenses.SharedExpense", b =>
                {
                    b.OwnsOne("FamilyFinance.Domain.ValueObjects.Money", "MonthlyAmount", b1 =>
                        {
                            b1.Property<Guid>("SharedExpenseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("MonthlyAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("SharedExpenseId");

                            b1.ToTable("SharedExpenses");

                            b1.WithOwner()
                                .HasForeignKey("SharedExpenseId");
                        });

                    b.OwnsOne("FamilyFinance.Domain.ValueObjects.BiweeklySchedule", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("SharedExpenseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("PaymentDay")
                                .HasColumnType("int")
                                .HasColumnName("PaymentDay");

                            b1.HasKey("SharedExpenseId");

                            b1.ToTable("SharedExpenses");

                            b1.WithOwner()
                                .HasForeignKey("SharedExpenseId");
                        });

                    b.Navigation("MonthlyAmount")
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("FamilyFinance.Domain.Aggregates.FamilyBudget.Member", b =>
                {
                    b.HasOne("FamilyFinance.Domain.Aggregates.FamilyBudget.FamilyGroup", null)
                        .WithMany("Members")
                        .HasForeignKey("FamilyGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FamilyFinance.Domain.ValueObjects.Money", "MonthlyNetIncome", b1 =>
                        {
                            b1.Property<Guid>("MemberId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("MonthlyIncomeAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("MonthlyIncomeCurrency");

                            b1.HasKey("MemberId");

                            b1.ToTable("Members");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.OwnsOne("FamilyFinance.Domain.ValueObjects.ProportionRatio", "Proportion", b1 =>
                        {
                            b1.Property<Guid>("MemberId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasPrecision(8, 4)
                                .HasColumnType("decimal(8,4)")
                                .HasColumnName("ProportionValue");

                            b1.HasKey("MemberId");

                            b1.ToTable("Members");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.Navigation("MonthlyNetIncome")
                        .IsRequired();

                    b.Navigation("Proportion")
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyFinance.Domain.Aggregates.Credits.CreditLine", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("FamilyFinance.Domain.Aggregates.FamilyBudget.FamilyGroup", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
